development: &development
  adapter: postgresql
  database: wareware_development
  encoding: utf8
test:
  <<: *development
  database: wareware_test
production:
  <<: *development
  database: wareware_production
staging:
  <<: *development
  database: wareware_staging
